"""Deterministic notebook summary and Markdown audit report renderers.

After a cloning run completes, the gateway generates:

1. A concise HTML notebook entry for the experiment body (via
   ``amend_my_experiment_after_approval``).
2. A comprehensive Markdown audit report as a file attachment.

Both are deterministic — they use captured step/protocol/validation data
as the source of truth.  The LLM may contribute rationale/explanation
(via the ``llm_rationale`` parameter of ``render_notebook_summary()``)
but cannot invent or override facts.

Missing facts render as ``N/A`` or ``not checked`` — never invented.
"""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Any


# --- public renderers --------------------------------------------------------


def render_notebook_summary(
    sequences: list[dict[str, Any]],
    sources: list[dict[str, Any]],
    primers: list[dict[str, Any]],
    validation_bundle: dict[str, Any],
    protocol_result: dict[str, Any] | None = None,
    step_manifests: list[dict[str, Any]] | None = None,
    artifact_ids: dict[str, int | None] | None = None,
    goal: str = "",
    method: str = "",
    llm_rationale: str = "",
) -> str:
    """Render a concise HTML notebook entry for the experiment body.

    Returns an HTML string suitable for appending via
    ``amend_my_experiment_after_approval``.
    """
    sections: list[str] = []

    sections.append(f"<h4>🔬 Cloning summary — {_na_or(method, 'assembly')}</h4>")
    sections.append(_notebook_header(goal))
    sections.append(_notebook_intro(method, sequences, sources))
    sections.append(_notebook_regions(sequences, sources))
    sections.append(_notebook_primers(primers))
    sections.append(_notebook_pcr_details(step_manifests, sequences))
    sections.append(_notebook_protocol(protocol_result))
    sections.append(_notebook_construct(sequences, sources))
    sections.append(_notebook_validation(validation_bundle))
    sections.append(_notebook_attachments(artifact_ids))
    if llm_rationale:
        sections.append(_notebook_rationale(llm_rationale))

    return "\n".join(sections)


def render_cloning_audit_report_markdown(
    sequences: list[dict[str, Any]],
    sources: list[dict[str, Any]],
    primers: list[dict[str, Any]],
    validation_bundle: dict[str, Any],
    step_manifests: list[dict[str, Any]],
    protocol_result: dict[str, Any] | None = None,
    artifact_ids: dict[str, int | None] | None = None,
    goal: str = "",
    method: str = "",
    warnings: list[dict[str, Any]] | None = None,
    rollback_instructions: str = "",
) -> str:
    """Render a comprehensive Markdown audit report.

    Returns a Markdown string suitable for file attachment.
    """
    parts: list[str] = []

    parts.append(_audit_header(method, goal))
    parts.append(_audit_step_timeline(step_manifests))
    parts.append(_audit_intermediate_products(sequences, sources))
    parts.append(_audit_primer_table(primers))
    parts.append(_audit_protocol(protocol_result))
    parts.append(_audit_fallback_assumptions(protocol_result))
    parts.append(_audit_validation(validation_bundle))
    parts.append(_audit_provenance(sources))
    parts.append(_audit_warnings_section(warnings))
    parts.append(_audit_attachments(artifact_ids))
    parts.append(_audit_rollback(rollback_instructions))
    parts.append("---\n*Report generated by Lab Copilot Gateway*")

    return "\n\n".join(parts)


# --- notebook helpers (HTML) -------------------------------------------------


def _na_or(value: str, fallback: str = "N/A") -> str:
    """Return value or fallback if empty."""
    return value if value and value.strip() else fallback


def _bool_or(seq: dict[str, Any], key: str) -> bool | None:
    """Return a boolean field or None."""
    v = seq.get(key)
    return v if isinstance(v, bool) else None


def _int_or_seq(seq: dict[str, Any], key: str) -> int | None:
    """Return an int field or None."""
    v = seq.get(key)
    return v if isinstance(v, int) else None


def _notebook_header(goal: str) -> str:
    if not goal or not goal.strip():
        return ""
    return f"<p><strong>Objective:</strong> {_escape_html(goal)}</p>"


def _escape_html(text: str) -> str:
    """Escape HTML special characters."""
    return (
        text.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
    )


def _notebook_intro(
    method: str,
    sequences: list[dict[str, Any]],
    sources: list[dict[str, Any]],
) -> str:
    """Render the intro paragraph: method, input count."""
    method_label = _na_or(method, "cloning")
    seq_count = len(sequences) if isinstance(sequences, list) else 0
    src_count = len(sources) if isinstance(sources, list) else 0
    return (
        f"<p>Method: <strong>{_escape_html(method_label)}</strong> &mdash; "
        f"{seq_count} sequence(s), {src_count} source(s).</p>"
    )


def _notebook_regions(
    sequences: list[dict[str, Any]],
    sources: list[dict[str, Any]],
) -> str:
    """Render selected regions from template sources."""
    lines: list[str] = []
    if not isinstance(sources, list) or not sources:
        return ""
    for src in sources:
        if not isinstance(src, dict):
            continue
        if src.get("type") == "DatabaseSource":
            continue
        region = _format_source_region(src)
        if region:
            lines.append(f"<li>{_escape_html(region)}</li>")

    if not lines:
        return ""
    return (
        "<p><strong>Selected regions:</strong></p>\n<ul>\n"
        + "\n".join(lines)
        + "\n</ul>"
    )


def _format_source_region(src: dict[str, Any]) -> str | None:
    """Format a single source's region info as text."""
    output_name = src.get("output_name") or src.get("id", "")
    inputs = src.get("input")
    if not isinstance(inputs, list) or not inputs:
        return None

    parts: list[str] = []
    for inp in inputs:
        if not isinstance(inp, dict):
            continue
        seq_id = inp.get("sequence")
        start = inp.get("start")
        end = inp.get("end")
        strand = inp.get("strand")
        sub = f"sequence {seq_id}"
        if start is not None:
            sub += f" [{start}"
            if end is not None:
                sub += f"..{end}"
            sub += "]"
        if strand:
            sub += f", {strand} strand"
        parts.append(sub)

    if not parts:
        return None
    return f"{output_name}: {', '.join(parts)}"


def _notebook_primers(primers: list[dict[str, Any]]) -> str:
    """Render the primer table."""
    if not isinstance(primers, list) or not primers:
        return ""

    rows: list[str] = []
    for primer in primers:
        if not isinstance(primer, dict):
            continue
        name = primer.get("name", "N/A")
        seq = primer.get("sequence", "")
        if isinstance(seq, str) and len(seq) > 30:
            seq = seq[:30] + "…"
        elif not seq:
            seq = "N/A"
        tm = primer.get("tm") or primer.get("melting_temperature") or "N/A"
        rows.append(
            f"<tr><td>{_escape_html(str(name))}</td>"
            f"<td><code>{_escape_html(str(seq))}</code></td>"
            f"<td>{tm}</td></tr>"
        )

    return (
        "<p><strong>Primers:</strong></p>\n"
        '<table border="1" cellpadding="4" cellspacing="0">\n'
        "<thead><tr><th>Name</th><th>Sequence (5′→3′)</th><th>Tm (°C)</th></tr></thead>\n"
        "<tbody>\n" + "\n".join(rows) + "\n</tbody>\n</table>"
    )


def _format_pcr_product_line(
    out_ref: str,
    sequences: list[dict[str, Any]],
    template_str: str,
) -> str:
    """Format a single PCR product line as HTML."""
    seq = _find_sequence_by_id(sequences, out_ref)
    length = _int_or_seq(seq, "length") if seq else None
    name = seq.get("name", out_ref) if seq else out_ref
    length_str = f"{length} bp" if length else "N/A"
    return (
        f"<li>Product <strong>{_escape_html(str(name))}</strong> "
        f"({length_str}) — template: {_escape_html(template_str)}</li>"
    )


def _notebook_pcr_details(
    step_manifests: list[dict[str, Any]] | None,
    sequences: list[dict[str, Any]],
) -> str:
    """Render PCR product details."""
    if not isinstance(step_manifests, list):
        return ""

    lines: list[str] = []
    for step in step_manifests:
        if not isinstance(step, dict):
            continue
        if step.get("operation_type") != "pcr":
            continue
        template_str = _pcr_template_str(step)
        for out_ref in step.get("output_refs", []):
            lines.append(_format_pcr_product_line(out_ref, sequences, template_str))

    if not lines:
        return ""
    return (
        "<p><strong>PCR products:</strong></p>\n<ul>\n" + "\n".join(lines) + "\n</ul>"
    )


def _pcr_template_str(step: dict[str, Any]) -> str:
    """Build a template description string from a PCR step manifest."""
    template_refs = step.get("template_refs", [])
    if template_refs:
        return ", ".join(str(r) for r in template_refs)
    return "N/A"


def _notebook_protocol(protocol_result: dict[str, Any] | None) -> str:
    """Render protocol-backed conditions."""
    if not protocol_result or not isinstance(protocol_result, dict):
        return ""

    best = protocol_result.get("best_match")
    if not isinstance(best, dict):
        return ""

    lines: list[str] = []
    title = best.get("title", "Protocol")
    annealing = best.get("annealing_temperature_rule")
    cycles = best.get("cycle_count_guidance")

    if annealing or cycles:
        lines.append(
            f"<li><strong>{_escape_html(str(title))}</strong>: "
            f"annealing {_escape_html(str(annealing or 'N/A'))}, "
            f"{_escape_html(str(cycles or 'N/A'))} cycles</li>"
        )

    if not lines:
        return ""
    return (
        "<p><strong>Protocol conditions:</strong></p>\n<ul>\n"
        + "\n".join(lines)
        + "\n</ul>"
    )


def _notebook_construct(
    sequences: list[dict[str, Any]],
    sources: list[dict[str, Any]],
) -> str:
    """Render the final construct info."""
    if not isinstance(sequences, list) or not sequences:
        return ""

    final = _find_last_leaf_or_content(sequences, sources)
    if not final:
        return ""

    name = final.get("name", "Final construct")
    length = _int_or_seq(final, "length")
    circular = _bool_or(final, "circular")

    topology = "circular" if circular else "linear"
    length_str = f"{length} bp" if length else "N/A"
    return (
        f"<p><strong>Final construct:</strong> {_escape_html(str(name))} "
        f"&mdash; {length_str}, {topology}</p>"
    )


def _notebook_validation(validation_bundle: dict[str, Any]) -> str:
    """Render validation status."""
    if not validation_bundle or not isinstance(validation_bundle, dict):
        return ""

    is_approved = validation_bundle.get("is_approved", False)
    blockers = validation_bundle.get("blockers", [])
    warnings_list = validation_bundle.get("warnings", [])

    blocker_count = (
        len(blockers)
        if isinstance(blockers, list)
        else validation_bundle.get("blocker_count", 0)
    )
    warning_count = (
        len(warnings_list)
        if isinstance(warnings_list, list)
        else validation_bundle.get("warning_count", 0)
    )

    status_icon = "✅" if is_approved else "❌"
    status_text = "Pass" if is_approved else "Blocked"
    return (
        f"<p><strong>Validation:</strong> {status_icon} {status_text} "
        f"&mdash; {blocker_count} blocker(s), {warning_count} warning(s)</p>"
    )


def _notebook_attachments(artifact_ids: dict[str, int | None] | None) -> str:
    """Render attachment ID links."""
    if not artifact_ids or not isinstance(artifact_ids, dict):
        return ""

    lines: list[str] = []
    label_map = {
        "genbank": "GenBank",
        "history_json": "History JSON",
        "audit_report": "Audit report",
    }
    for key, label in label_map.items():
        aid = artifact_ids.get(key)
        if aid is not None:
            lines.append(f"<li>{_escape_html(label)}: upload id={aid}</li>")

    if not lines:
        return ""
    return "<p><strong>Attachments:</strong></p>\n<ul>\n" + "\n".join(lines) + "\n</ul>"


def _notebook_rationale(llm_rationale: str) -> str:
    """Render an optional LLM rationale section."""
    if not llm_rationale or not llm_rationale.strip():
        return ""
    return (
        "<details>\n"
        f"<summary><strong>AI-generated rationale</strong></summary>\n"
        f"<p>{_escape_html(llm_rationale)}</p>\n"
        "</details>"
    )


# --- audit report helpers (Markdown) -----------------------------------------


def _timestamp() -> str:
    """Return current UTC timestamp."""
    return datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")


def _audit_header(method: str, goal: str) -> str:
    """Render the audit report header."""
    method_str = _na_or(method, "cloning")
    goal_str = _na_or(goal, "not specified")
    return (
        f"# Cloning Audit Report\n\n"
        f"**Date:** {_timestamp()}\n\n"
        f"**Method:** {method_str}\n\n"
        f"**Goal:** {goal_str}"
    )


def _audit_step_timeline(step_manifests: list[dict[str, Any]]) -> str:
    """Render the full step timeline."""
    if not isinstance(step_manifests, list) or not step_manifests:
        return "## Step Timeline\n\nNo step manifests recorded."

    rows: list[str] = []
    for i, step in enumerate(step_manifests, start=1):
        if not isinstance(step, dict):
            continue
        op_type = step.get("operation_type", "N/A")
        label = step.get("operation_label", "N/A")
        status = step.get("status", "N/A")
        inputs = ", ".join(str(r) for r in (step.get("input_refs") or [])) or "—"
        outputs = ", ".join(str(r) for r in (step.get("output_refs") or [])) or "—"
        rows.append(
            f"| {i} | {_escape_md(str(op_type))} "
            f"| {_escape_md(str(label))} "
            f"| {_escape_md(str(status))} "
            f"| {_escape_md(inputs)} "
            f"| {_escape_md(outputs)} |"
        )

    if not rows:
        return "## Step Timeline\n\nNo step manifests recorded."

    header = "| # | Operation | Label | Status | Inputs | Outputs |"
    sep = "|---|-----------|-------|--------|--------|---------|"
    return "## Step Timeline\n\n" + header + "\n" + sep + "\n" + "\n".join(rows)


def _escape_md(text: str) -> str:
    """Escape pipe characters for Markdown tables."""
    return text.replace("|", "\\|")


def _audit_intermediate_products(
    sequences: list[dict[str, Any]],
    sources: list[dict[str, Any]],
) -> str:
    """Render all intermediate products/fragments."""
    if not isinstance(sequences, list) or not sequences:
        return "## Intermediate Products\n\nNo sequences recorded."

    # Identify the final construct to distinguish intermediates.
    final = _find_last_leaf_or_content(sequences, sources)
    final_id = _int_or_none(final.get("id")) if final else None

    rows: list[str] = []
    for seq in sequences:
        if not isinstance(seq, dict):
            continue
        sid = seq.get("id", "N/A")
        name = seq.get("name", "N/A")
        length = seq.get("length", "N/A")
        circular = _bool_or(seq, "circular")
        topology = (
            "circular" if circular else ("linear" if circular is not None else "N/A")
        )
        role = (
            "final"
            if final_id is not None and _int_or_none(sid) == final_id
            else "intermediate"
        )
        rows.append(
            f"| {_escape_md(str(sid))} | {_escape_md(str(name))} "
            f"| {_escape_md(str(length))} bp | {topology} | {role} |"
        )

    if not rows:
        return "## Intermediate Products\n\nNo sequences recorded."

    header = "| ID | Name | Length | Topology | Role |"
    sep = "|----|------|--------|----------|------|"
    return "## Intermediate Products\n\n" + header + "\n" + sep + "\n" + "\n".join(rows)


def _escape_md_table(text: str) -> str:
    return text.replace("|", "\\|")


def _audit_primer_table(primers: list[dict[str, Any]]) -> str:
    """Render the primer properties table."""
    if not isinstance(primers, list) or not primers:
        return "## Primers\n\nNo primers in this cloning run."

    rows: list[str] = []
    for primer in primers:
        if not isinstance(primer, dict):
            continue
        name = primer.get("name", "N/A")
        seq = primer.get("sequence", "N/A")
        length = len(seq) if isinstance(seq, str) and seq else "N/A"
        tm = primer.get("tm") or primer.get("melting_temperature") or "N/A"
        gc = primer.get("gc_content") or primer.get("gc_percent") or "N/A"
        rows.append(
            f"| {_escape_md(str(name))} "
            f"| `{_escape_md(str(seq))}` "
            f"| {length} "
            f"| {tm} "
            f"| {gc} |"
        )

    header = "| Name | Sequence (5′→3′) | Length (nt) | Tm (°C) | GC (%) |"
    sep = "|------|-------------------|-------------|---------|--------|"
    return "## Primers\n\n" + header + "\n" + sep + "\n" + "\n".join(rows)


def _audit_protocol(protocol_result: dict[str, Any] | None) -> str:
    """Render protocol entries used."""
    if not protocol_result or not isinstance(protocol_result, dict):
        return "## Protocol\n\nNo protocol lookup performed."

    best = protocol_result.get("best_match")
    if not isinstance(best, dict):
        return "## Protocol\n\nNo protocol match found."

    lines: list[str] = [
        "| Property | Value |",
        "|----------|-------|",
        f"| Title | {_escape_md(str(best.get('title', 'N/A')))} |",
        f"| Manufacturer | {_escape_md(str(best.get('manufacturer', 'N/A')))} |",
        f"| Catalog # | {_escape_md(str(best.get('catalog_number', 'N/A')))} |",
        f"| Method type | {_escape_md(str(best.get('method_type', 'N/A')))} |",
        f"| Reagent | {_escape_md(str(best.get('reagent_product_name', 'N/A')))} |",
        f"| Annealing temp rule | {_escape_md(str(best.get('annealing_temperature_rule', 'N/A')))} |",
        f"| Extension rate | {_escape_md(str(best.get('extension_rate', 'N/A')))} |",
        f"| Cycle count | {_escape_md(str(best.get('cycle_count_guidance', 'N/A')))} |",
        f"| Match confidence | {_escape_md(str(best.get('match_confidence', 'N/A')))} |",
    ]
    return "## Protocol\n\n" + "\n".join(lines)


def _audit_fallback_assumptions(protocol_result: dict[str, Any] | None) -> str:
    """Render unsupported fallback assumptions."""
    if not protocol_result or not isinstance(protocol_result, dict):
        return "## Fallback Assumptions\n\nProtocol lookup was not performed."

    fallback_used = protocol_result.get("fallback_used", False)
    if not fallback_used:
        return "## Fallback Assumptions\n\nNo fallback — approved protocol was used."

    warnings_list = protocol_result.get("warnings", [])
    items = (
        "\n".join(f"- {_escape_md(str(w))}" for w in warnings_list)
        if warnings_list
        else "- Protocol lookup used fallback conditions."
    )
    return "## Fallback Assumptions\n\n" + items


def _audit_validation(validation_bundle: dict[str, Any]) -> str:
    """Render the full validation bundle."""
    if not validation_bundle or not isinstance(validation_bundle, dict):
        return "## Validation\n\nNo validation performed."

    is_approved = validation_bundle.get("is_approved", False)
    status = "**APPROVED** ✅" if is_approved else "**BLOCKED** ❌"

    checks = validation_bundle.get("checks", [])
    rows: list[str] = []
    for check in checks:
        if not isinstance(check, dict):
            continue
        cid = check.get("check_id", "N/A")
        label = check.get("label", "N/A")
        level = check.get("level", "N/A")
        status_val = check.get("status", "N/A")
        detail = check.get("detail", "")
        rows.append(
            f"| {_escape_md(str(cid))} "
            f"| {_escape_md(str(label))} "
            f"| {_escape_md(str(level))} "
            f"| {_escape_md(str(status_val))} "
            f"| {_escape_md(str(detail))} |"
        )

    if not rows:
        return f"## Validation\n\n**Status:** {status}\n\nNo checks recorded."

    header = "| Check ID | Label | Level | Status | Detail |"
    sep = "|----------|-------|-------|--------|--------|"
    return (
        f"## Validation\n\n**Status:** {status}\n\n"
        + header
        + "\n"
        + sep
        + "\n"
        + "\n".join(rows)
    )


def _format_provenance_input_desc(src: dict[str, Any]) -> str:
    """Format the input sequence description for a source."""
    inputs = src.get("input")
    if not isinstance(inputs, list) or not inputs:
        return "—"
    seq_refs: list[str] = []
    for inp in inputs:
        if isinstance(inp, dict):
            seq_refs.append(str(inp.get("sequence", "?")))
    return ", ".join(seq_refs) if seq_refs else "—"


def _format_provenance_row(src: dict[str, Any]) -> str | None:
    """Format a single provenance source row."""
    if not isinstance(src, dict):
        return None
    sid = src.get("id", "N/A")
    src_type = src.get("type", "N/A")
    output_name = src.get("output_name", "—")
    input_desc = _format_provenance_input_desc(src)
    return (
        f"| {_escape_md(str(sid))} "
        f"| {_escape_md(str(src_type))} "
        f"| {_escape_md(str(output_name))} "
        f"| {_escape_md(input_desc)} |"
    )


def _audit_provenance(sources: list[dict[str, Any]]) -> str:
    """Render the OpenCloning provenance source tree."""
    if not isinstance(sources, list) or not sources:
        return "## Provenance\n\nNo source tracking data recorded."

    rows = [_format_provenance_row(src) for src in sources]
    rows = [r for r in rows if r is not None]

    if not rows:
        return "## Provenance\n\nNo source tracking data recorded."

    header = "| Source ID | Type | Output Name | Input Sequence(s) |"
    sep = "|-----------|------|-------------|-------------------|"
    return "## Provenance\n\n" + header + "\n" + sep + "\n" + "\n".join(rows)


def _audit_warnings_section(warnings: list[dict[str, Any]] | None) -> str:
    """Render general warnings."""
    if not isinstance(warnings, list) or not warnings:
        return "## Warnings\n\nNone."
    items: list[str] = []
    for w in warnings:
        if isinstance(w, dict) and w.get("message"):
            items.append(f"- {_escape_md(str(w['message']))}")
        else:
            items.append(f"- {_escape_md(str(w))}")
    return "## Warnings\n\n" + "\n".join(items)


def _audit_attachments(artifact_ids: dict[str, int | None] | None) -> str:
    """Render final attachment IDs."""
    if not artifact_ids or not isinstance(artifact_ids, dict):
        return "## Attachments\n\nNo attachment IDs recorded."

    lines: list[str] = [
        "| File | Upload ID |",
        "|------|-----------|",
    ]
    label_map = {
        "genbank": "GenBank artifact",
        "history_json": "Cloning history JSON",
        "audit_report": "Audit report (this file)",
    }
    for key, label in label_map.items():
        aid = artifact_ids.get(key)
        if aid is not None:
            lines.append(f"| {label} | {aid} |")
        else:
            lines.append(f"| {label} | not uploaded |")

    return "## Attachments\n\n" + "\n".join(lines)


def _audit_rollback(rollback_instructions: str) -> str:
    """Render rollback notes."""
    default = "To undo: delete the GenBank attachment and the history JSON from the experiment, then restore the experiment body from the previous state."
    text = (
        rollback_instructions
        if rollback_instructions and rollback_instructions.strip()
        else default
    )
    return "## Rollback\n\n" + _escape_md(text)


# --- shared helpers ----------------------------------------------------------


def _find_sequence_by_id(
    sequences: list[dict[str, Any]], seq_id: str | Any
) -> dict[str, Any] | None:
    """Find a sequence dict by its id field."""
    if not isinstance(sequences, list):
        return None
    for seq in sequences:
        if isinstance(seq, dict) and str(seq.get("id", "")) == str(seq_id):
            return seq
    return None


def _collect_seq_input_ids(
    sources: list[dict[str, Any]],
) -> set[Any]:
    """Collect all sequence IDs referenced as source inputs."""
    ids: set[Any] = set()
    for src in sources:
        if not isinstance(src, dict):
            continue
        inputs = src.get("input")
        if not isinstance(inputs, list):
            continue
        for inp in inputs:
            if isinstance(inp, dict):
                rid = inp.get("sequence")
                if rid is not None:
                    ids.add(rid)
    return ids


def _first_with_content(
    seqs: list[dict[str, Any]],
) -> dict[str, Any] | None:
    """Return the last sequence with file_content, or last entry."""
    for seq in reversed(seqs):
        if isinstance(seq, dict) and seq.get("file_content"):
            return seq
    return seqs[-1] if seqs else None


def _find_last_leaf_or_content(
    sequences: list[dict[str, Any]],
    sources: list[dict[str, Any]],
) -> dict[str, Any] | None:
    """Find the final construct: leaf or last with file_content."""
    if not isinstance(sequences, list) or not sequences:
        return None
    input_ids = _collect_seq_input_ids(sources)
    leaves = [
        s for s in sequences if isinstance(s, dict) and s.get("id") not in input_ids
    ]
    if leaves:
        result = _first_with_content(leaves)
        if result is not None:
            return result
        return leaves[-1]
    return _first_with_content(sequences)


def _int_or_none(value: Any) -> int | None:
    """Return int value or None."""
    if isinstance(value, bool):
        return None
    if isinstance(value, int):
        return value
    return None
