"""Execution-plan schema v0 (C38).

Defines the first formal execution-plan JSON schema and binding semantics.
A plan is a structured representation of a multi-step lab workflow that the
user approves before the gateway executes it deterministically.

The plan object is:

- **JSON-serializable** — the orchestrator sends plans as JSON; the gateway
  parses, validates, and executes them.
- **Hash-stable** — canonical serialization produces a deterministic SHA-256
  hash that binds the plan to the approval token (same pattern as
  ``compute_args_hash`` in ``approval.py``).
- **Validatable** — the gateway rejects plans with missing fields, invalid
  risk tiers, raw endpoint URLs, or inconsistent approval modes.

This module is the schema/contract layer. Execution (C39) and result
reporting (C40) build on top of it.

See ``docs/plans/lab-copilot-nlux-execution-plan-architecture.md`` →
"Execution plan object sketch" for the architectural rationale.
"""

from __future__ import annotations

import hashlib
import json
from dataclasses import dataclass, field
from enum import IntEnum
from typing import Any


# --- risk tiers --------------------------------------------------------------


class PlanRiskTier(IntEnum):
    """Risk tier for an execution plan.

    Tiers map to the progressive planning model from the architecture doc:

        1 = single_record_edit: lightweight preview, eLabFTW revision rollback
        2 = batch_edit: formal change-set, per-step audit
        3 = computational: OpenCloning workflow, artifact writeback
        4 = hardware: Wallac/BentoLab, preflight + abort
        5 = autonomous: future, strict budgets + kill switches
    """

    SINGLE_RECORD_EDIT = 1
    BATCH_EDIT = 2
    COMPUTATIONAL = 3
    HARDWARE = 4
    AUTONOMOUS = 5

    @property
    def label(self) -> str:
        return self.name.lower()

    @property
    def approval_mode(self) -> str:
        """How approval works for this tier."""
        if self <= PlanRiskTier.SINGLE_RECORD_EDIT:
            return "lightweight_preview"
        if self <= PlanRiskTier.COMPUTATIONAL:
            return "formal_change_set"
        return "strong_execution"


# --- forbidden raw-endpoint fields (same guard as tool registry) -------------

_FORBIDDEN_RAW_ENDPOINT_FIELDS: frozenset[str] = frozenset(
    {
        "url",
        "endpoint",
        "endpoint_url",
        "raw_endpoint",
        "raw_url",
        "http_method",
        "http_path",
    }
)


# --- exceptions --------------------------------------------------------------


class PlanValidationError(Exception):
    """Raised when a plan fails validation.

    ``errors`` is the list of individual validation failure messages.
    """

    def __init__(self, errors: list[str]) -> None:
        self.errors = errors
        super().__init__(f"plan validation failed: {'; '.join(errors)}")


# --- plan step ---------------------------------------------------------------


@dataclass(frozen=True)
class PlanStep:
    """One step in an execution plan.

    A step references a gateway tool by name (never a raw endpoint URL).
    The ``args`` dict is the tool invocation arguments — the same shape
    the ``/invoke`` endpoint accepts.  ``record_id`` identifies the target
    record (e.g. ``"elabftw:experiment:42"``) for audit context.
    """

    tool_name: str
    record_id: str | None = None
    args: dict[str, Any] = field(default_factory=dict)
    preview_type: str | None = None  # "diff", "summary", "artifact", None

    def to_dict(self) -> dict[str, Any]:
        # Reason: falsy values (None, "", {}) are intentionally elided so
        # the canonical JSON is minimal and stable — from_dict restores them
        # to their defaults (None / {}).  This keeps the hash deterministic
        # regardless of whether the caller set record_id="" or omitted it.
        d: dict[str, Any] = {"tool_name": self.tool_name}
        if self.record_id is not None:
            d["record_id"] = self.record_id
        if self.args:
            d["args"] = self.args
        if self.preview_type is not None:
            d["preview_type"] = self.preview_type
        return d

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "PlanStep":
        return cls(
            tool_name=str(data.get("tool_name", "")),
            record_id=data.get("record_id"),
            args=data.get("args", {}) if isinstance(data.get("args"), dict) else {},
            preview_type=data.get("preview_type"),
        )


# --- plan --------------------------------------------------------------------


@dataclass(frozen=True)
class Plan:
    """A formal execution plan (C38 schema v0).

    Fields:
        plan_id: unique identifier (generated by the orchestrator).
        intent: natural-language description of what the plan does.
        anchor: context anchor — {system, record_type, record_id} of the
            eLabFTW record the plan was launched from.
        risk_tier: operational risk tier (determines approval mode).
        summary: user-visible one-line summary shown before approval.
        reads: read-only steps (search/read operations).
        writes: mutating steps (edits, uploads, writebacks).
        artifacts: generated artifacts (e.g. OpenCloning designs).
        approval_required: whether the user must approve before execution.
        rollback: rollback strategy description (e.g. "eLabFTW revision history").

    All fields are user-visible before approval — the plan IS the approval
    surface.  The user approves the plan, not hidden tool calls.
    """

    plan_id: str
    intent: str
    anchor: dict[str, Any]
    risk_tier: PlanRiskTier
    summary: str
    reads: list[PlanStep] = field(default_factory=list)
    writes: list[PlanStep] = field(default_factory=list)
    artifacts: list[dict[str, Any]] = field(default_factory=list)
    approval_required: bool = True
    rollback: str | None = None

    # --- serialization ---

    def to_dict(self) -> dict[str, Any]:
        return {
            "plan_id": self.plan_id,
            "intent": self.intent,
            "anchor": self.anchor,
            "risk_tier": self.risk_tier.label,
            "summary": self.summary,
            "reads": [s.to_dict() for s in self.reads],
            "writes": [s.to_dict() for s in self.writes],
            "artifacts": self.artifacts,
            "approval": {
                "mode": self.risk_tier.approval_mode,
                "required": self.approval_required,
            },
            "rollback": self.rollback,
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "Plan":
        """Construct a Plan from a dict (e.g. JSON from the orchestrator).

        Raises ``PlanValidationError`` if the risk_tier is invalid.
        """
        risk_label = str(data.get("risk_tier", "")).strip().upper()
        try:
            risk_tier = PlanRiskTier[risk_label]
        except KeyError:
            valid = [t.label for t in PlanRiskTier]
            raise PlanValidationError(
                [f"risk_tier {risk_label!r} not valid (allowed: {valid})"]
            )

        approval = data.get("approval", {})
        if not isinstance(approval, dict):
            approval = {}

        reads_raw = data.get("reads", [])
        writes_raw = data.get("writes", [])
        reads = (
            [
                PlanStep.from_dict(s)
                if isinstance(s, dict)
                else PlanStep(tool_name=str(s))
                for s in reads_raw
            ]
            if isinstance(reads_raw, list)
            else []
        )
        writes = (
            [
                PlanStep.from_dict(s)
                if isinstance(s, dict)
                else PlanStep(tool_name=str(s))
                for s in writes_raw
            ]
            if isinstance(writes_raw, list)
            else []
        )

        artifacts = data.get("artifacts", [])
        if not isinstance(artifacts, list):
            artifacts = []

        anchor = data.get("anchor", {})
        if not isinstance(anchor, dict):
            anchor = {}

        return cls(
            plan_id=str(data.get("plan_id", "")),
            intent=str(data.get("intent", "")),
            anchor=anchor,
            risk_tier=risk_tier,
            summary=str(data.get("summary", "")),
            reads=reads,
            writes=writes,
            artifacts=artifacts,
            approval_required=bool(approval.get("required", True)),
            rollback=data.get("rollback"),
        )

    # --- hashing ---

    def canonical_json(self) -> str:
        """Canonical JSON serialization for hashing.

        Uses ``sort_keys=True, separators=(",", ":")`` — the same canonical
        form as ``compute_args_hash`` in ``approval.py``.  Produces a
        byte-stable encoding independent of dict insertion order.
        """
        return json.dumps(self.to_dict(), sort_keys=True, separators=(",", ":"))

    def hash(self) -> str:
        """SHA-256 hex of the canonical serialization.

        This hash binds the plan to the approval token.  Any change to the
        plan content produces a different hash, invalidating a prior approval.
        """
        return hashlib.sha256(self.canonical_json().encode("utf-8")).hexdigest()


def compute_plan_hash(plan: Plan) -> str:
    """Standalone function — mirrors ``compute_args_hash`` for ergonomics."""
    return plan.hash()


# --- validation --------------------------------------------------------------


def validate_plan(plan: Plan) -> list[str]:
    """Validate a plan.  Returns a list of error strings (empty = valid).

    Checks:
        1. ``plan_id`` is non-empty.
        2. ``intent`` is non-empty.
        3. ``summary`` is non-empty.
        4. ``anchor`` has ``system``, ``record_type``, ``record_id``.
        5. Every write step has a ``tool_name`` and ``record_id``.
        6. No step carries a forbidden raw-endpoint field.
        7. Hardware/autonomous plans must specify a ``rollback`` strategy.
        8. Plans with writes must have ``approval_required=True``.
    """
    errors: list[str] = []

    # 1. plan_id
    if not plan.plan_id or not plan.plan_id.strip():
        errors.append("plan_id must be non-empty")

    # 2. intent
    if not plan.intent or not plan.intent.strip():
        errors.append("intent must be non-empty")

    # 3. summary
    if not plan.summary or not plan.summary.strip():
        errors.append("summary must be non-empty")

    # 4. anchor
    anchor = plan.anchor
    if not isinstance(anchor, dict):
        errors.append("anchor must be a dict")
    else:
        for key in ("system", "record_type", "record_id"):
            if not anchor.get(key):
                errors.append(f"anchor.{key} must be non-empty")

    # 5. Write steps must have tool_name and record_id
    for i, step in enumerate(plan.writes):
        if not step.tool_name or not step.tool_name.strip():
            errors.append(f"writes[{i}].tool_name must be non-empty")
        if not step.record_id:
            errors.append(f"writes[{i}].record_id must be non-empty")

    # Also check reads have tool_name
    for i, step in enumerate(plan.reads):
        if not step.tool_name or not step.tool_name.strip():
            errors.append(f"reads[{i}].tool_name must be non-empty")

    # 6. No forbidden raw-endpoint fields in any step's args
    for group_name, steps in (("reads", plan.reads), ("writes", plan.writes)):
        for i, step in enumerate(steps):
            for forbidden in _FORBIDDEN_RAW_ENDPOINT_FIELDS:
                if forbidden in step.args:
                    errors.append(
                        f"{group_name}[{i}].args contains forbidden "
                        f"raw-endpoint field {forbidden!r}"
                    )

    # 7. Hardware/autonomous plans must specify rollback
    if plan.risk_tier >= PlanRiskTier.HARDWARE and not plan.rollback:
        errors.append(f"risk_tier {plan.risk_tier.label} requires a rollback strategy")

    # 8. Plans with writes must require approval
    if plan.writes and not plan.approval_required:
        errors.append("plans with writes must have approval_required=True")

    return errors


def validate_or_raise(plan: Plan) -> None:
    """Validate a plan, raising ``PlanValidationError`` if invalid."""
    errors = validate_plan(plan)
    if errors:
        raise PlanValidationError(errors)


# --- user-visible fields -----------------------------------------------------

# All fields in the plan are user-visible before approval — the plan IS the
# approval surface.  This constant documents that explicitly so future
# contributors don't accidentally hide fields from the user.
USER_VISIBLE_FIELDS: tuple[str, ...] = (
    "plan_id",
    "intent",
    "anchor",
    "risk_tier",
    "summary",
    "reads",
    "writes",
    "artifacts",
    "approval",
    "rollback",
)


# --- fixtures ----------------------------------------------------------------
#
# Canonical plan fixtures for testing and documentation.  These represent
# the four plan archetypes from the architecture doc.


def fixture_simple_edit() -> Plan:
    """A lightweight single-record edit plan.

    Example: "Review and correct this notebook entry."
    Risk tier: SINGLE_RECORD_EDIT (lightweight preview, eLabFTW revision rollback).
    """
    return Plan(
        plan_id="plan-fixture-simple-edit",
        intent="Review and correct this notebook entry",
        anchor={
            "system": "elabftw",
            "record_type": "experiment",
            "record_id": "123",
        },
        risk_tier=PlanRiskTier.SINGLE_RECORD_EDIT,
        summary="Correct grammar and clarify the PCR setup section.",
        reads=[
            PlanStep(
                tool_name="elabftw.read_current_experiment",
                record_id="elabftw:experiment:123",
            ),
        ],
        writes=[
            PlanStep(
                tool_name="elabftw.edit_experiment_section",
                record_id="elabftw:experiment:123",
                args={"old_body_hash": "abc123", "new_body": "<p>corrected</p>"},
                preview_type="diff",
            ),
        ],
        artifacts=[],
        approval_required=True,
        rollback="eLabFTW revision history",
    )


def fixture_batch_edit() -> Plan:
    """A formal batch change-set plan.

    Example: "Update all protocols that mention reagent X."
    Risk tier: BATCH_EDIT (formal change-set, per-step audit).
    """
    return Plan(
        plan_id="plan-fixture-batch-edit",
        intent="Update all protocols that mention reagent X",
        anchor={
            "system": "elabftw",
            "record_type": "experiment",
            "record_id": "100",
        },
        risk_tier=PlanRiskTier.BATCH_EDIT,
        summary="Replace 'reagent X' with 'reagent Y' across 3 experiments.",
        reads=[
            PlanStep(
                tool_name="elabftw.search_my_experiments",
                args={"query": "reagent X", "limit": 20},
            ),
            PlanStep(
                tool_name="elabftw.read_experiment_by_id",
                record_id="elabftw:experiment:101",
            ),
            PlanStep(
                tool_name="elabftw.read_experiment_by_id",
                record_id="elabftw:experiment:102",
            ),
            PlanStep(
                tool_name="elabftw.read_experiment_by_id",
                record_id="elabftw:experiment:103",
            ),
        ],
        writes=[
            PlanStep(
                tool_name="elabftw.edit_experiment_section",
                record_id="elabftw:experiment:101",
                args={"old_body_hash": "hash101", "new_body": "<p>reagent Y</p>"},
                preview_type="diff",
            ),
            PlanStep(
                tool_name="elabftw.edit_experiment_section",
                record_id="elabftw:experiment:102",
                args={"old_body_hash": "hash102", "new_body": "<p>reagent Y</p>"},
                preview_type="diff",
            ),
            PlanStep(
                tool_name="elabftw.edit_experiment_section",
                record_id="elabftw:experiment:103",
                args={"old_body_hash": "hash103", "new_body": "<p>reagent Y</p>"},
                preview_type="diff",
            ),
        ],
        artifacts=[],
        approval_required=True,
        rollback="eLabFTW revision history",
    )


def fixture_bentolab() -> Plan:
    """A hardware execution plan for BentoLab PCR (C43).

    Example: "Run this PCR protocol on BentoLab."
    Risk tier: HARDWARE (preflight + lock + abort + strong approval).

    The plan includes preflight reads (status + validate + dry-run) before
    the write step (submit_pcr_run).  Execution remains blocked by policy
    in V1 (tier 5 denied by default).
    """
    return Plan(
        plan_id="plan-fixture-bentolab",
        intent="Run this PCR protocol on BentoLab",
        anchor={
            "system": "elabftw",
            "record_type": "experiment",
            "record_id": "400",
        },
        risk_tier=PlanRiskTier.HARDWARE,
        summary="Validate profile, dry-run, submit PCR run on BentoLab.",
        reads=[
            PlanStep(
                tool_name="bentolab.get_status",
            ),
            PlanStep(
                tool_name="bentolab.validate_pcr_profile",
                args={
                    "profile": {
                        "initial_denaturation": {"temperature": 95, "duration": 30}
                    }
                },
            ),
            PlanStep(
                tool_name="bentolab.dry_run_pcr_profile",
                args={
                    "profile": {
                        "initial_denaturation": {"temperature": 95, "duration": 30}
                    }
                },
            ),
        ],
        writes=[
            PlanStep(
                tool_name="bentolab.submit_pcr_run",
                record_id="elabftw:experiment:400",
                args={
                    "profile": {
                        "initial_denaturation": {"temperature": 95, "duration": 30}
                    }
                },
                preview_type="summary",
            ),
        ],
        artifacts=[],
        approval_required=True,
        rollback="Abort via BentoLab HTTP API kill switch; results are non-reversible",
    )


def fixture_opencloning() -> Plan:
    """A computational OpenCloning workflow plan.

    Example: "Design a cloning strategy for this insert."
    Risk tier: COMPUTATIONAL (formal change-set, artifact writeback).
    """
    return Plan(
        plan_id="plan-fixture-opencloning",
        intent="Design a cloning strategy for this insert",
        anchor={
            "system": "elabftw",
            "record_type": "experiment",
            "record_id": "200",
        },
        risk_tier=PlanRiskTier.COMPUTATIONAL,
        summary="Simulate Gibson assembly and attach the resulting GenBank file.",
        reads=[
            PlanStep(
                tool_name="elabftw.read_current_experiment",
                record_id="elabftw:experiment:200",
            ),
            PlanStep(
                tool_name="opencloning.parse_sequence_file",
                args={"file_format": "genbank"},
            ),
        ],
        writes=[
            PlanStep(
                tool_name="opencloning.writeback_artifact",
                record_id="elabftw:experiment:200",
                args={"artifact_filename": "construct.gb"},
                preview_type="artifact",
            ),
        ],
        artifacts=[
            {
                "kind": "genbank",
                "filename": "construct.gb",
                "description": "Gibson assembly product",
            },
        ],
        approval_required=True,
        rollback="Delete attached artifact from eLabFTW",
    )


def fixture_hardware() -> Plan:
    """A hardware execution plan (Wallac plate reader).

    Example: "Run this Wallac generated protocol."
    Risk tier: HARDWARE (preflight + abort + strong approval).

    Note: hardware execution remains blocked by policy in V1 (C42).
    This fixture demonstrates the plan shape for when it is enabled.
    """
    return Plan(
        plan_id="plan-fixture-hardware-wallac",
        intent="Run this Wallac generated protocol on the Victor2",
        anchor={
            "system": "elabftw",
            "record_type": "experiment",
            "record_id": "300",
        },
        risk_tier=PlanRiskTier.HARDWARE,
        summary="Execute Wallac generated protocol with preflight checks.",
        reads=[
            PlanStep(
                tool_name="wallac.get_status",
            ),
            PlanStep(
                tool_name="wallac.validate_generated_protocol",
                args={"protocol_package": {"method": "endpoint", "layout": "96"}},
            ),
        ],
        writes=[
            PlanStep(
                tool_name="wallac.submit_generated_protocol",
                record_id="elabftw:experiment:300",
                args={"protocol_package": {"method": "endpoint", "layout": "96"}},
                preview_type="summary",
            ),
        ],
        artifacts=[],
        approval_required=True,
        rollback="Abort via hardware kill switch; results are non-reversible",
    )


def fixture_autonomous() -> Plan:
    """An autonomous execution plan (C29).

    Example: "Monitor cell growth — read instrument status and log to eLabFTW."
    Risk tier: AUTONOMOUS (strong execution, bounded by budget + kill switches).

    When autonomy is enabled (``LAB_COPILOT_AUTONOMY_ENABLED=1``), the plan
    executor skips the plan-level approval consume for this tier.  All other
    safety checks (body drift, append-only, audit) remain enforced.
    """

    return Plan(
        plan_id="plan-fixture-autonomous",
        intent="Monitor cell growth — read instrument status and log to eLabFTW",
        anchor={
            "system": "elabftw",
            "record_type": "experiment",
            "record_id": "500",
        },
        risk_tier=PlanRiskTier.AUTONOMOUS,
        summary="Read Wallac status and append reading to experiment body.",
        reads=[
            PlanStep(
                tool_name="wallac.get_status",
            ),
        ],
        writes=[
            PlanStep(
                tool_name="elabftw.edit_experiment_section",
                record_id="elabftw:experiment:500",
                args={"old_body_hash": "hash500", "new_body": "<p>reading logged</p>"},
                preview_type="diff",
            ),
        ],
        artifacts=[],
        approval_required=True,
        rollback="eLabFTW revision history",
    )
